# Generated by Django 5.0.4 on 2024-05-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecommerce_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="phone",
            field=models.CharField(max_length=15, verbose_name="Номер телефона"),
        ),
    ]
