# Generated by Django 5.0.4 on 2024-12-21 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=191, verbose_name='Название категории')),
                ('image', models.ImageField(upload_to='category_images/', verbose_name='Фото')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=191, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('phone', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('address', models.CharField(max_length=191, verbose_name='Город, адрес')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время заказа')),
                ('paid', models.BooleanField(default=False, verbose_name='Оплачен')),
                ('delivered', models.BooleanField(default=False, verbose_name='Доставлен')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=191, verbose_name='Название товара')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='products_images/', verbose_name='Фото')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PCyber.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Изменение')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PCyber.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PCyber.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Оформленный заказ',
                'verbose_name_plural': 'Оформленные заказы',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PCyber.product')),
            ],
        ),
    ]
